apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fetcher
  name: fetcher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fetcher
    spec:
      containers:
      - args:
        - -c 
        - /mnt/config.json 
        - fetcher 
        image: infinex/pyspider:latest
        name: fetcher
        ports:
        - containerPort: 24444
        resources: {}
        volumeMounts:
        - name: "config"
          mountPath: "/mnt/config.json"
          subPath: "config.json"
      restartPolicy: Always
      volumes:
        - name: "config"
          configMap:
            name: "config"
status: {}
