apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phantomjs
  name: phantomjs
spec:
  clusterIP: None
  ports:
  - name: "25555"
    port: 25555
    targetPort: 25555
  selector:
    app: phantomjs
status:
  loadBalancer: {}
