apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: processor
  name: processor
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: processor
status:
  loadBalancer: {}
