apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webui
  name: webui
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: webui
status:
  loadBalancer: {}
